### ISSUE TITLE
Build Issues on MACOSX

### ISSUE THREAD

**Issue by iosmichael** [uoip/g2opy#33]
I think there is some build issues with the current library on MAC OSX. Once the python library compiled and installed. An error raises when importing the library

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/g2o.cpython-37m-darwin.so, 2): Symbol not found: __ZN3g2o10HyperGraph12UnassignedIdE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/g2o.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/g2o.cpython-37m-darwin.so`

I dont know how to solve this problem. Help will be appreciated.

**Comment by OptimusNuke** [comment]
Your problem is the "Symbol not found: __ZN3g2o10HyperGraph12UnassignedIdE"-part of the message. This problem got already solved by George Hotz in his livestream while he was programming a slam (he named his project twitchslam). For more Information on how to solve this problem look up for issue #1 .
It should be the answer. The livestream on how he solved this (your) problem is yet online - you can find it on youtube. It's a 10h stream, your problem is at around 2h40 and takes up to half an hour to solve for him.
Hopefully I could help
